carloscuesta/react-native-error-boundary

README.md
=> 📝 Note type of errors component catches

README.md, package.json
=> 📝 Add expo example

FAQ.md, README.md
Related to #82.
Adds a FAQ section that links to a separate document. Additionally, adds my question and @carloscuesta's answer (slightly touched up—I hope you don't mind!) as the first question-and-answer pair.
=> doc: add FAQ (#82)

package.json, src/__tests__/__snapshots__/errorBoundary.spec.js.snap, src/__tests__/errorBoundary.spec.js, yarn.lock
Update test specs and the devDependencies we use to test ErrorBoundary component.
=> ✅ Update tests suites

package.json, src/ErrorBoundary/FallbackComponent/index.js, src/ErrorBoundary/index.js, src/__tests__/__snapshots__/errorBoundary.spec.js.snap, yarn.lock
=> ✨ Replace Standard with ESLint

.github/workflows/npm-publish.yml
Automates the process of publishing the releases on GitHub and writing the changelog.
=> 👷 Automate GitHub release publish

.github/workflows/npm-publish.yml
This pull request updates the release title we set from GitHub Actions when publishing a new version
=> 👷 Update release title

.github/ISSUE_TEMPLATES/bug-report.yml, .github/ISSUE_TEMPLATES/feature-request.yml
Hey!
This PR adds two issue templates to the repo:
- Bug reports
- Feature requests
=> 📝 Add `ISSUE_TEMPLATES`

docs/docs/api/errorboundary.md, docs/docs/api/fallbackcomponent.md, docs/docs/faq.md, docs/docs/introduction.md, docs/docs/usage/logging-errors.md, docs/docs/usage/rendering-custom-fallback.md
Improving the docs site a bit ✨
=> 📝 Improve docs

.github/dependabot.yml
Hey! 👋🏼 
Enabling Dependabot for `docs` site
=> 🔧 Enable dependabot for `docs`

docs/docs/usage/logging-errors.md
Fixing a minor typo in the documentation
=> 📝 Handler was defined but not used

.github/workflows/ci.yml, .github/workflows/npm-publish.yml
Hey! 👋🏼 
This PR updates both actions to the latest version.
=> ⬆️ Bump `actions/setup-node` and `actions/checkout`

.husky/pre-commit, package.json, src/ErrorBoundary/FallbackComponent/index.tsx, src/ErrorBoundary/FallbackComponent/styles.ts, src/ErrorBoundary/index.tsx, src/__tests__/errorBoundary.spec.tsx, yarn.lock
Hey! 👋🏼 
This PR adds `prettier` to the project along with `lint-staged` and `husky`.
=> 🧑‍💻 Setup `prettier` with `lint-staged` and `husky`

.github/dependabot.yml, docs/docusaurus.config.js
👋🏼 
This PR enables search functionality in the `react-native-error-boundary` docs:
To do list:
=> ✨ Enable search in docs with Algolia `docsearch`

docs/docusaurus.config.js
=> 🔧 Update docusarus siteUrl

.github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/question.yml
Hey! :wave:
This PR adds a new issue template for questions and disables blank issues.
=> 📝 Add issue template for questions

package.json, src/__tests__/__snapshots__/errorBoundary.spec.tsx.snap, src/__tests__/errorBoundary.spec.tsx, yarn.lock
Hey! 👋🏼 
This PR refactors the tests of this library to use `react-native-testing-library`.
=> ♻️ Refactor tests with `react-native-testing-library`

README.md
Updated React website link in readme
it just points to the latest Docs website
=> ✏️ Update `reactjs.org` documentation link

docs/package.json, docs/yarn.lock
👋🏼 
This PR updates the documentation site dependencies
=> ⬆️ Update `docs` dependencies

.github/workflows/ci.yml, package.json, yarn.lock
Hey! 👋🏼 
Replacing the deprecated `codecov-node` module with the GitHub Action.
=> ♻️ Use `codecov` uploader

package.json, yarn.lock
Hey! 👋🏼 
This PR updates the `@react-native/babel-preset` dependency which also fixes the transform issue that happened here:
https://github.com/carloscuesta/react-native-error-boundary/pull/891
=> ⬆️ Update `@react-native/babel-preset`

.github/dependabot.yml
Hey! 👋🏼 
This PR groups dependabot updates.
=> 🔧 Group Dependabot updates in `dev` and `deps`
